from pathlib import Path

path = Path(__file__).with_name("main.tex")
text = path.read_text(encoding="utf-8")

replacements = {
r"""Sparse delayed rewards create a classical temporal credit-assignment problem: the learner must infer which earlier actions influenced the final outcome (Sutton and Barto, 2018). In language-model RLVR, GRPO reduces critic memory by estimating advantages relative to a group of sampled solutions, but it still assigns one sequence-level signal broadly across the generated response (Shao \textit{et al.}, 2024). Recent work has shown that this uniform broadcast can waste gradient on predictable tokens and dilute learning at informative positions. Entropy-Aware Policy Optimization, for example, identifies high-entropy tokens as important carriers of credit (He \textit{et al.}, 2026), while counterfactual reasoning paths provide step-sensitive comparisons that reduce gradient variance (Ding \textit{et al.}, 2026). Self-conditioned credit assignment instead derives token weights from the model's own verified trajectories (Shan \textit{et al.}, 2026).""":
r"""Sparse delayed rewards create a classical temporal credit-assignment problem: the learner must infer which earlier actions influenced the final outcome (Sutton and Barto, 2018). In language-model RLVR, GRPO estimates advantages relative to sampled solution groups but still broadcasts one sequence-level signal across the response (Shao \textit{et al.}, 2024). This may waste gradient on predictable tokens and dilute learning at informative positions. Entropy-Aware Policy Optimization identifies high-entropy tokens as important credit carriers (He \textit{et al.}, 2026), while counterfactual reasoning paths provide step-sensitive comparisons that reduce gradient variance (Ding \textit{et al.}, 2026). Self-conditioned credit assignment instead derives token weights from verified trajectories (Shan \textit{et al.}, 2026).""",
r"""The project's main contribution will be a controlled empirical test of this distinction. Ground-truth-credit environments allow us to measure whether a reliability proxy predicts credit error rather than merely correlating with token entropy. Factorial ablations will hold the estimated direction fixed while changing the local KL controller, and vice versa, isolating whether improvements arise from gradient weighting or trust-region allocation. We will also study failure cases by deliberately relocating or corrupting credit signals. Theoretical work will seek stability or regret-style statements under explicitly stated assumptions; it is an exploratory objective rather than a claimed result. If successful, the project will offer a lightweight, interpretable mechanism for improving robustness without requiring a process reward model. If performance does not improve, the calibration and failure analysis will still identify when local reliability control is ineffective, providing a useful boundary for future RLVR research.""":
r"""The project's main contribution will be a controlled empirical test of this distinction. Ground-truth-credit environments let us test whether a reliability proxy predicts credit error rather than merely correlating with entropy. Factorial ablations will hold the estimated direction fixed while changing the local KL controller, and vice versa, isolating gradient weighting from trust-region allocation. We will also relocate or corrupt credit signals to expose failure cases. Theory will seek stability or regret-style statements under explicit assumptions; this is an exploratory objective, not a claimed result. Whether or not performance improves, the calibration analysis will identify when local reliability control is useful and establish a boundary for future RLVR research.""",
r"""HUANG YUXUAN leads project integration, supervisor communication and the final narrative. LIU YIPU leads OMD/KL theory and checks the formula--code mapping. XIE HAOXIANG builds the controlled environments, oracle credit and reliability estimators. ZHONG YIFAN implements baselines, RC-OMD variants and monitoring infrastructure. LI YUFEI manages configurations, multi-seed experiments, statistical analysis and figures. All members review literature, verify results and prepare the presentation; every major output receives an independent cross-review. Responsibilities may be rebalanced after the Day~8 review while preserving clear ownership and reproducibility.""":
r"""HUANG YUXUAN coordinates the project and final report. LIU YIPU leads theory; XIE HAOXIANG, environments and estimators; ZHONG YIFAN, algorithms and infrastructure; LI YUFEI, experiments and analysis. All members review evidence and prepare the presentation. Major outputs receive cross-review, and workloads may be rebalanced after Day~8.""",
}

for old, new in replacements.items():
    if old not in text:
        raise RuntimeError("Expected text not found")
    text = text.replace(old, new)

path.write_text(text, encoding="utf-8")
